background="#1B1B23"
text="#a493b8"
subtle="#5c5c5c"
warning-text="#f92672"
text-special-one="#9257a2"
text-special-two="#d97cf3"
top-bar-background="#954096"
top-bar-text="#f8f8f2"
status-bar-background="#683a69"
status-bar-text="#f8f8f2"
status-bar-view-background="#98329a"
status-bar-view-text="#f8f8f2"
list-selected-background="#5c3e60"
list-selected-text="#d7a6f7"
list-selected-inactive-background="#24242d"
list-selected-inactive-text="#a493b8"
controls-text="#f8f8f8"
controls-highlight="#d382d1"
autocomplete-background="#272822"
autocomplete-text="#f8f8f8"
autocomplete-selected-background="#98329a"
autocomplete-selected-text="#f8f8f8"
button-color-one="#c372da"
button-color-two="#272822"
timeline-name-background="#1b1b23"
timeline-name-text="#9257a2"
command-text="#f8f8f2"
